### ISSUE TITLE
Multi-GPU training

### ISSUE THREAD

**Issue by xuxy09** [shubham-goel/ucmr#10]
Hi,

I am trying to run the training code. The code runs well with a single GPU, but it fails with multiple GPUs:
`File "/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 54, in forward
    assert all(map(lambda i: i.is_cuda, inputs))
AssertionError` 

The error comes from `File "/ucmr/src/experiments/camOpt_shape.py", line 635, in forward
    self.return_dict = self.model(input_dict)`

I notice that there is data-parallel in your code so I suppose you use multiple GPUs during training. Could you please let me know how to solve this problem?

Thanks!

**Comment by shubham-goel** [comment]
Hi @xuxy09. Sorted now. FYI: Though the code supports it, I didn't use multi-gpu training in any of my experiments.
