### ISSUE TITLE
What are the correct arguments for save_obj_file when trying to save the generated mesh to disk?

### ISSUE THREAD

**Issue by nightfarrow** [shubham-goel/ucmr#15]
Hi,

I'm trying to use  `save_obj_file` to save the generated 3D mesh to disk.

First, I place

`from .utils import mesh as mesh_util` 

near the top of demo.py.

Then, in demo.py `visualize` 

I put:

`mesh_util.save_obj_file('trythis.obj', pred_util.MeshPredictor(opts).verts, pred_util.MeshPredictor(opts).faces)`

in method. But it looks like this just saves the mesh of the template bird, perhaps. The resulting obj is not the shape of the input image bird.

What arguments should be used for `save_obj_file` to save the generated mesh of the current image, not the template image? In other words, if you run,

```
python -m src.demo \
    --pred_pose \
    --pretrained_network_path=cachedir/snapshots/cam/e400_cub_train_cam4/pred_net_600.pth \
    --shape_path=cachedir/template_shape/bird_template.npy\
    --img_path demo_data/birdie1.png
```

what arguments for `save_obj_file` would work to save the generated birdie1.png mesh obj file to disk?

Thank you!!

**Comment by shubham-goel** [comment]
Hi @nightfarrow. Your command is saving the template mesh because `MeshPredictor.verts` contains the vertices of the template mesh.

You need to pass the predicted vertices (`outputs['verts'][0]`). Using this before calling `visualize()` works:
```
mesh_util.save_obj_file('demo.obj', outputs['verts'][0], predictor.faces)
```
