### ISSUE TITLE
Request for pca Code

### ISSUE THREAD

**Issue by hideonInternet** [shubham-goel/ucmr#16]
Nice work! Could you please provide the PCA code used for analyzing the learned space of the train set? Thanks a lot!

**Comment by shubham-goel** [comment]
Hi, I only have my research code to offer (which isn't very clean and well factored): [shape_pca_generic.py.zip](https://github.com/shubham-goel/ucmr/files/5862951/shape_pca_generic.py.zip). This assumes that all the shapes to which a PCA model has to be fit, are already saved to disk. But it shouldn't be too hard to interface this with [benchmark.py](https://github.com/shubham-goel/ucmr/blob/master/src/experiments/benchmark.py#L204).
