### ISSUE TITLE
Benchmark results visualization

### ISSUE THREAD

**Issue by alexj94** [shubham-goel/ucmr#18]
Hi,
I have a question about the visualization rendering of the benchmark results. I tested correctly your model using the "benchmark.py" script with the released pretrained weights both for CUB birds and PASCAL car class. Since I'm trying to reproduce also the textured results of your network, I noticed that you use NMR as the visualization renderer and SoftRas as the prediction one in the network. Is this procedure the same you used for generating the results of your ECCV2020 paper?
Just to give you a reference to the code I'm talking about the function render at:
https://github.com/shubham-goel/ucmr/blob/3c335e2fad006117ed0ef7766823cbc45e7a6f15/src/experiments/benchmark.py#L130
in which you use the vis_rend variable defined at https://github.com/shubham-goel/ucmr/blob/3c335e2fad006117ed0ef7766823cbc45e7a6f15/src/nnutils/predictor.py#L75
Thanks in advance for your response.

**Comment by shubham-goel** [comment]
Hi @alexj94 . That's right, I used SoftRas for training but NMR for generating visualizations in the paper because the images looked better. It also let me reuse a lot of code from [CMR](https://github.com/akanazawa/cmr/blob/master/utils/bird_vis.py). Let me know if you have any more questions!
