### ISSUE TITLE
How to create cachedir/template_shape

### ISSUE THREAD

**Issue by felixboevr** [shubham-goel/ucmr#19]
Hi Shubham, 

could you please give me a hint how you created bird_template.npy and the other template shapes for cars, shoes etc? 

Did you convert an .obj file in blender like explained here https://youtu.be/KHZ01dXNyHs?t=710 or is there an easier way to get the .npy files for template shapes? 

Thank you

**Comment by shubham-goel** [comment]
Hi @felixboevr. I started by downloading existing meshes. E.g. I started with the template bird mesh from CSM. 

I first rotated and scaled the meshes in Blender s.t. the plane of symmetry is the y-z axis. I then simplified my mesh and symmetrized it about the y-z plane. Here is some (ugly) research code for this that uses functions defined in [utils/mesh.py](https://github.com/shubham-goel/ucmr/blob/29c012f6ff022dfedb301a72cc772b7dee1500f5/src/utils/mesh.py#L427-L648).

[process_mesh.py.zip](https://github.com/shubham-goel/ucmr/files/6261763/process_mesh.py.zip)
