### ISSUE TITLE
Pascal3D IoU Evaluation

### ISSUE THREAD

**Issue by monniert** [shubham-goel/ucmr#24]
Hi Shubham, thanks for releasing this great project! 

I am trying to compare against the proposed approach, how is IoU computed for the Pascal3D results (Table 3)? 

In the code, following `docs/training.md` then `src.experiments.benchmarks`, it seems to output 2D silhouette IoU, does it correspond to the IoU reported in Table 3? Or is it a 3D IoU whose calculation is not in the released code?

Thanks for the help, Tom

**Comment by shubham-goel** [comment]
Hi @monniert. Thanks for asking. The 3D IoU calculation was not part of the initial release. I've updated the `pascal` branch with instructions on how to compute 3DIoU. Please see [here](https://github.com/shubham-goel/ucmr/blob/pascal/docs/training.md).

Please let me know if this works for you!

Best,
Shubham

**Comment by yangyouzi** [comment]
Hello, No module named 'soft' appears when I try to run the project_ How to solve the error of renderer ''? Is the file missing?

**Comment by yangyouzi** [comment]
Hello, “No module named  'soft_renderer'” appears when I try to run the project_ How to solve the error ? Is the file missing?

**Comment by yangyouzi** [comment]
Hello,I have an error here when running the NMR file, displaying "module 'soft_renderer' has no attribute 'SoftRenderer'"，I checked that there is no softrender.py in the "soft_render" library，How to solve the problem？
![c2a6c8b21dee1105138a7e3511cd912](https://user-images.githubusercontent.com/117643890/208578324-3470efed-083f-4ba7-be53-bb3d7317f915.png)
![0b56b243d821e91ca38e85b54a0204c](https://user-images.githubusercontent.com/117643890/208578330-2b021796-f3bd-4f83-a7c7-07406faca5c7.png)
![227e6a3d8882e6f80e162904d6714c2](https://user-images.githubusercontent.com/117643890/208578339-0c675a4a-1427-44f5-bacc-0a693f85452a.png)
