### ISSUE TITLE
Missing loss weights values

### ISSUE THREAD

**Issue by alexj94** [shubham-goel/ucmr#5]
Hi,
thank you for releasing the code.
I'm trying to reproduce your results on the CUB dataset, but I can't find the weights assigned to the different losses.
Could you please add them to the code?

**Comment by shubham-goel** [comment]
Hi @alexj94. You can find the weights in [this config file](https://github.com/shubham-goel/ucmr/blob/master/configs/cub-train.cfg). To reproduce results, please follow [docs/training.md](https://github.com/shubham-goel/ucmr/blob/master/docs/training.md).
