### ISSUE TITLE
File missing: "'cachedir/template_shape/bird_template.npy"

### ISSUE THREAD

**Issue by xuxy09** [shubham-goel/ucmr#9]
Hi,

I want to run your demo. However, it seems one key file "'cachedir/template_shape/bird_template.npy" is missing. Could you please let me know where to download it?

Thanks.

**Comment by kinrinwin** [comment]
Wait, what was the answer to this, please? I'm having this issue too. Thank you.

**Comment by normster** [comment]
@kinrinwin download annotations and template meshes with: 

```
wget https://people.eecs.berkeley.edu/~shubham-goel/projects/ucmr/cachedir.tar.gz && tar -vzxf cachedir.tar.gz
```

(from the [training](https://github.com/shubham-goel/ucmr/blob/master/docs/training.md) instructions)
